import { EmotionStyleSheet } from './types';

export interface VisageFaces {
  // Badge.ts
  Badge?: EmotionStyleSheet;
  // Banner.tsx
  Banner?: EmotionStyleSheet;
  // Banner.tsx
  BannerRibbon?: EmotionStyleSheet;
  // Backdrop.tsx
  BaseBackdrop?: EmotionStyleSheet;
  // Dialog.tsx
  BaseDialog?: EmotionStyleSheet;
  // Modal.tsx
  BaseModal?: EmotionStyleSheet;
  // Popover.tsx
  BasePopover?: EmotionStyleSheet;
  // Box.ts
  Box?: EmotionStyleSheet;
  // Button.ts
  Button?: EmotionStyleSheet;
  // Card.tsx
  CardBase?: EmotionStyleSheet;
  // Card.tsx
  CardContent?: EmotionStyleSheet;
  // Card.tsx
  CardTouchable?: EmotionStyleSheet;
  // Checkbox.tsx
  CheckboxControl?: EmotionStyleSheet;
  // Checkbox.tsx
  CheckboxLabel?: EmotionStyleSheet;
  // Checkbox.tsx
  CheckboxLabelText?: EmotionStyleSheet;
  // Checkbox.tsx
  CheckboxWrapper?: EmotionStyleSheet;
  // Chip.tsx
  Chip?: EmotionStyleSheet;
  // Chip.tsx
  ChipDeleter?: EmotionStyleSheet;
  // CloseButton.tsx
  CloseButton?: EmotionStyleSheet;
  // Layout.ts
  Column?: EmotionStyleSheet;
  // Layout.ts
  Container?: EmotionStyleSheet;
  // Divider.tsx
  DividerBase?: EmotionStyleSheet;
  // Divider.tsx
  DividerLabel?: EmotionStyleSheet;
  // Divider.tsx
  DividerLine?: EmotionStyleSheet;
  // FieldSet.tsx
  FieldSet?: EmotionStyleSheet;
  // FieldSet.tsx
  FieldSetLegend?: EmotionStyleSheet;
  // FileInput.tsx
  FileInputBaseControl?: EmotionStyleSheet;
  // FileInput.tsx
  FileInputBox?: EmotionStyleSheet;
  // FileInput.tsx
  FileInputControl?: EmotionStyleSheet;
  // Fixed.ts
  Fixed?: EmotionStyleSheet;
  // Flex.ts
  Flex?: EmotionStyleSheet;
  // Grid.ts
  Grid?: EmotionStyleSheet;
  // Group.ts
  Group?: EmotionStyleSheet;
  // Header.ts
  Header?: EmotionStyleSheet;
  // Heading.tsx
  HeadingBase?: EmotionStyleSheet;
  // Image.tsx
  ImageContainer?: EmotionStyleSheet;
  // Image.tsx
  Img?: EmotionStyleSheet;
  // TextInput.tsx
  InputExtraElement?: EmotionStyleSheet;
  // Label.tsx
  Label?: EmotionStyleSheet;
  // Link.ts
  Link?: EmotionStyleSheet;
  // List.tsx
  ListContainer?: EmotionStyleSheet;
  // List.tsx
  ListHeader?: EmotionStyleSheet;
  // List.tsx
  ListItem?: EmotionStyleSheet;
  // List.tsx
  ListItemLink?: EmotionStyleSheet;
  // List.tsx
  ListItemsContainer?: EmotionStyleSheet;
  // Loading.tsx
  LoadingProgressBar?: EmotionStyleSheet;
  // Loading.tsx
  LoadingProgressBarProgress?: EmotionStyleSheet;
  // Menu.tsx
  MenuBase?: EmotionStyleSheet;
  // Menu.tsx
  MenuItemBase?: EmotionStyleSheet;
  // Overlay.tsx
  OverlayDiv?: EmotionStyleSheet;
  // Paragraph.tsx
  Paragraph?: EmotionStyleSheet;
  // Paragraph.tsx
  ParagraphSkeleton?: EmotionStyleSheet;
  // ProgressBar.tsx
  ProgressBar?: EmotionStyleSheet;
  // ProgressBar.tsx
  ProgressBarProgress?: EmotionStyleSheet;
  // Radio.tsx
  RadioControl?: EmotionStyleSheet;
  // Radio.tsx
  RadioLabel?: EmotionStyleSheet;
  // Radio.tsx
  RadioLabelText?: EmotionStyleSheet;
  // Radio.tsx
  RadioWrapper?: EmotionStyleSheet;
  // Layout.ts
  Row?: EmotionStyleSheet;
  // Spinner.tsx
  SpinnerSvgBase?: EmotionStyleSheet;
  // SvgIcon.tsx
  SvgIconBase?: EmotionStyleSheet;
  // Tabs.tsx
  TabNavigationAnchor?: EmotionStyleSheet;
  // Tabs.tsx
  TabNavigationList?: EmotionStyleSheet;
  // Tabs.tsx
  TabNavigationListItem?: EmotionStyleSheet;
  // Text.tsx
  Text?: EmotionStyleSheet;
  // TextArea.tsx
  TextArea?: EmotionStyleSheet;
  // TextArea.tsx
  TextAreaBase?: EmotionStyleSheet;
  // TextArea.tsx
  TextAreaShadow?: EmotionStyleSheet;
  // TextInput.tsx
  TextInputBase?: EmotionStyleSheet;
  // TextInput.tsx
  TextInputControl?: EmotionStyleSheet;
  // TextInput.tsx
  TextInputControlBase?: EmotionStyleSheet;
  // Text.tsx
  TextSkeleton?: EmotionStyleSheet;
  // Toast.tsx
  Toast?: EmotionStyleSheet;
  // Toast.tsx
  ToastManager?: EmotionStyleSheet;
  // Toggle.tsx
  ToggleContainer?: EmotionStyleSheet;
  // Toggle.tsx
  ToggleControl?: EmotionStyleSheet;
  // Toggle.tsx
  ToggleLabel?: EmotionStyleSheet;
  // Toggle.tsx
  Toggler?: EmotionStyleSheet;
  [componentName: string]: EmotionStyleSheet | undefined;
}
