import { EmotionStyleSheet } from './types';

export interface VisageFaces {
  // Badge.ts
  Badge?: EmotionStyleSheet;
  // Banner.tsx
  Banner?: EmotionStyleSheet;
  // Banner.tsx
  BannerRibbon?: EmotionStyleSheet;
  // Quotes.ts
  Blockquote?: EmotionStyleSheet;
  // Box.ts
  Box?: EmotionStyleSheet;
  // Box.ts
  BoxSkeleton?: EmotionStyleSheet;
  // Button.ts
  Button?: EmotionStyleSheet;
  // Card.tsx
  Card?: EmotionStyleSheet;
  // Card.tsx
  CardContent?: EmotionStyleSheet;
  // Card.tsx
  CardTouchable?: EmotionStyleSheet;
  // Checkbox.tsx
  CheckboxControl?: EmotionStyleSheet;
  // Checkbox.tsx
  CheckboxLabel?: EmotionStyleSheet;
  // Checkbox.tsx
  CheckboxLabelText?: EmotionStyleSheet;
  // Checkbox.tsx
  CheckboxToggler?: EmotionStyleSheet;
  // Chip.tsx
  Chip?: EmotionStyleSheet;
  // Quotes.ts
  Cite?: EmotionStyleSheet;
  // CloseButton.tsx
  CloseButton?: EmotionStyleSheet;
  // Code.ts
  Code?: EmotionStyleSheet;
  // Layout.ts
  Column?: EmotionStyleSheet;
  // Layout.ts
  Container?: EmotionStyleSheet;
  // DataTable.tsx
  DataTable?: EmotionStyleSheet;
  // DataTable.tsx
  DataTableBody?: EmotionStyleSheet;
  // DataTable.tsx
  DataTableColumn?: EmotionStyleSheet;
  // DataTable.tsx
  DataTableColumnSkeleton?: EmotionStyleSheet;
  // DataTable.tsx
  DataTableFooter?: EmotionStyleSheet;
  // DataTable.tsx
  DataTableFooterRow?: EmotionStyleSheet;
  // DataTable.tsx
  DataTableHeader?: EmotionStyleSheet;
  // DataTable.tsx
  DataTableHeaderColumn?: EmotionStyleSheet;
  // DataTable.tsx
  DataTableHeaderRow?: EmotionStyleSheet;
  // DataTable.tsx
  DataTableNumericColumnSkeleton?: EmotionStyleSheet;
  // DataTable.tsx
  DataTableRow?: EmotionStyleSheet;
  // DescriptionList.tsx
  DescriptionList?: EmotionStyleSheet;
  // DescriptionList.tsx
  DescriptionListItemDescription?: EmotionStyleSheet;
  // DescriptionList.tsx
  DescriptionListItemTerm?: EmotionStyleSheet;
  // Dialog.tsx
  Dialog?: EmotionStyleSheet;
  // Divider.tsx
  Divider?: EmotionStyleSheet;
  // Divider.tsx
  DividerLabel?: EmotionStyleSheet;
  // Divider.tsx
  DividerLine?: EmotionStyleSheet;
  // Drawer.tsx
  Drawer?: EmotionStyleSheet;
  // Drawer.tsx
  DrawerBackdrop?: EmotionStyleSheet;
  // Text.tsx
  EmphasizedText?: EmotionStyleSheet;
  // FieldSet.tsx
  FieldSet?: EmotionStyleSheet;
  // FieldSet.tsx
  FieldSetHeading?: EmotionStyleSheet;
  // FieldSet.tsx
  FieldSetLegend?: EmotionStyleSheet;
  // FileInput.tsx
  FileInputBox?: EmotionStyleSheet;
  // FileInput.tsx
  FileInputControl?: EmotionStyleSheet;
  // FileInput.tsx
  FileInputControlBase?: EmotionStyleSheet;
  // Fixed.ts
  Fixed?: EmotionStyleSheet;
  // Flex.ts
  Flex?: EmotionStyleSheet;
  // Grid.ts
  Grid?: EmotionStyleSheet;
  // Group.ts
  Group?: EmotionStyleSheet;
  // Header.ts
  Header?: EmotionStyleSheet;
  // Heading.tsx
  Heading?: EmotionStyleSheet;
  // Image.tsx
  ImageContainer?: EmotionStyleSheet;
  // Image.tsx
  Img?: EmotionStyleSheet;
  // TextInput.tsx
  InputExtraElement?: EmotionStyleSheet;
  // Label.tsx
  Label?: EmotionStyleSheet;
  // Link.ts
  Link?: EmotionStyleSheet;
  // List.tsx
  ListContainer?: EmotionStyleSheet;
  // List.tsx
  ListHeader?: EmotionStyleSheet;
  // List.tsx
  ListItem?: EmotionStyleSheet;
  // List.tsx
  ListItemLink?: EmotionStyleSheet;
  // List.tsx
  ListItemsContainer?: EmotionStyleSheet;
  // Loading.tsx
  LoadingProgressBar?: EmotionStyleSheet;
  // Loading.tsx
  LoadingProgressBarProgress?: EmotionStyleSheet;
  // Menu.tsx
  Menu?: EmotionStyleSheet;
  // Menu.tsx
  MenuItem?: EmotionStyleSheet;
  // Modal.tsx
  Modal?: EmotionStyleSheet;
  // Modal.tsx
  ModalBackdrop?: EmotionStyleSheet;
  // Overlay.tsx
  OverlayDiv?: EmotionStyleSheet;
  // Paragraph.tsx
  Paragraph?: EmotionStyleSheet;
  // Paragraph.tsx
  ParagraphSkeleton?: EmotionStyleSheet;
  // Popover.tsx
  Popover?: EmotionStyleSheet;
  // Code.ts
  PreformattedCode?: EmotionStyleSheet;
  // ProgressBar.tsx
  ProgressBar?: EmotionStyleSheet;
  // ProgressBar.tsx
  ProgressBarProgress?: EmotionStyleSheet;
  // Quotes.ts
  Quote?: EmotionStyleSheet;
  // Radio.tsx
  RadioControl?: EmotionStyleSheet;
  // Radio.tsx
  RadioLabel?: EmotionStyleSheet;
  // Radio.tsx
  RadioLabelText?: EmotionStyleSheet;
  // Radio.tsx
  RadioToggler?: EmotionStyleSheet;
  // Layout.ts
  Row?: EmotionStyleSheet;
  // Text.tsx
  SmallText?: EmotionStyleSheet;
  // Spinner.tsx
  SpinnerSvgBase?: EmotionStyleSheet;
  // Text.tsx
  StrongText?: EmotionStyleSheet;
  // Scripts.ts
  Subscript?: EmotionStyleSheet;
  // Scripts.ts
  Superscript?: EmotionStyleSheet;
  // Svg.ts
  Svg?: EmotionStyleSheet;
  // SvgIcon.tsx
  SvgIconBase?: EmotionStyleSheet;
  // Tabs.tsx
  TabList?: EmotionStyleSheet;
  // Tabs.tsx
  TabNavigatonButton?: EmotionStyleSheet;
  // Text.tsx
  Text?: EmotionStyleSheet;
  // TextArea.tsx
  TextArea?: EmotionStyleSheet;
  // TextArea.tsx
  TextAreaBase?: EmotionStyleSheet;
  // TextInput.tsx
  TextInputBase?: EmotionStyleSheet;
  // TextInput.tsx
  TextInputControl?: EmotionStyleSheet;
  // TextInput.tsx
  TextInputControlBase?: EmotionStyleSheet;
  // Text.tsx
  TextSkeleton?: EmotionStyleSheet;
  // Toast.tsx
  Toast?: EmotionStyleSheet;
  // Toast.tsx
  ToastManager?: EmotionStyleSheet;
  // Toggle.tsx
  ToggleContainer?: EmotionStyleSheet;
  // Toggle.tsx
  ToggleControl?: EmotionStyleSheet;
  // Toggle.tsx
  ToggleLabel?: EmotionStyleSheet;
  // Toggle.tsx
  ToggleLabelText?: EmotionStyleSheet;
  // Toggle.tsx
  Toggler?: EmotionStyleSheet;
  [componentName: string]: EmotionStyleSheet | undefined;
}
