export interface VisageFaces {
  // Badge.ts
  Badge?: VisageStyleSheet;
  // Banner.tsx
  Banner?: VisageStyleSheet;
  // Banner.tsx
  BannerCloseButtonWrapper?: VisageStyleSheet;
  // Banner.tsx
  BannerContent?: VisageStyleSheet;
  // Banner.tsx
  BannerHeading?: VisageStyleSheet;
  // Banner.tsx
  BannerRibbon?: VisageStyleSheet;
  // Quotes.ts
  Blockquote?: VisageStyleSheet;
  // Box.tsx
  Box?: VisageStyleSheet;
  // Box.tsx
  BoxSkeleton?: VisageStyleSheet;
  // Button.ts
  Button?: VisageStyleSheet;
  // Card.tsx
  Card?: VisageStyleSheet;
  // Card.tsx
  CardContent?: VisageStyleSheet;
  // Card.tsx
  CardTouchable?: VisageStyleSheet;
  // Checkbox.tsx
  CheckboxControl?: VisageStyleSheet;
  // Checkbox.tsx
  CheckboxLabel?: VisageStyleSheet;
  // Checkbox.tsx
  CheckboxLabelText?: VisageStyleSheet;
  // Checkbox.tsx
  CheckboxToggler?: VisageStyleSheet;
  // Chip.tsx
  Chip?: VisageStyleSheet;
  // Chip.tsx
  ChipDeleteButton?: VisageStyleSheet;
  // Quotes.ts
  Cite?: VisageStyleSheet;
  // CloseButton.tsx
  CloseButton?: VisageStyleSheet;
  // Code.ts
  Code?: VisageStyleSheet;
  // Layout.ts
  Column?: VisageStyleSheet;
  // Layout.ts
  Container?: VisageStyleSheet;
  // DataTable.tsx
  DataTable?: VisageStyleSheet;
  // DataTable.tsx
  DataTableBody?: VisageStyleSheet;
  // DataTable.tsx
  DataTableColumn?: VisageStyleSheet;
  // DataTable.tsx
  DataTableColumnSkeleton?: VisageStyleSheet;
  // DataTable.tsx
  DataTableFooter?: VisageStyleSheet;
  // DataTable.tsx
  DataTableFooterRow?: VisageStyleSheet;
  // DataTable.tsx
  DataTableHeader?: VisageStyleSheet;
  // DataTable.tsx
  DataTableHeaderColumn?: VisageStyleSheet;
  // DataTable.tsx
  DataTableHeaderRow?: VisageStyleSheet;
  // DataTable.tsx
  DataTableNumericColumnSkeleton?: VisageStyleSheet;
  // DataTable.tsx
  DataTableRow?: VisageStyleSheet;
  // DescriptionList.tsx
  DescriptionList?: VisageStyleSheet;
  // DescriptionList.tsx
  DescriptionListItemDescription?: VisageStyleSheet;
  // DescriptionList.tsx
  DescriptionListItemTerm?: VisageStyleSheet;
  // Dialog.tsx
  Dialog?: VisageStyleSheet;
  // Dialog.tsx
  DialogCloseButton?: VisageStyleSheet;
  // Dialog.tsx
  DialogCloseButtonWrapper?: VisageStyleSheet;
  // Dialog.tsx
  DialogContent?: VisageStyleSheet;
  // Dialog.tsx
  DialogHeader?: VisageStyleSheet;
  // Dialog.tsx
  DialogHeading?: VisageStyleSheet;
  // Dialog.tsx
  DialogHeadingWrapper?: VisageStyleSheet;
  // Dialog.tsx
  DialogSubHeading?: VisageStyleSheet;
  // Divider.tsx
  Divider?: VisageStyleSheet;
  // Divider.tsx
  DividerLabel?: VisageStyleSheet;
  // Divider.tsx
  DividerLine?: VisageStyleSheet;
  // Drawer.tsx
  Drawer?: VisageStyleSheet;
  // Drawer.tsx
  DrawerBackdrop?: VisageStyleSheet;
  // Text.tsx
  EmphasizedText?: VisageStyleSheet;
  // FieldSet.tsx
  FieldSet?: VisageStyleSheet;
  // FieldSet.tsx
  FieldSetHeading?: VisageStyleSheet;
  // FieldSet.tsx
  FieldSetLegend?: VisageStyleSheet;
  // FileInput.tsx
  FileInputBase?: VisageStyleSheet;
  // FileInput.tsx
  FileInputControl?: VisageStyleSheet;
  // FileInput.tsx
  FileInputControlBase?: VisageStyleSheet;
  // Flex.ts
  Flex?: VisageStyleSheet;
  // FormField.tsx
  FormFieldWrapper?: VisageStyleSheet;
  // Grid.ts
  Grid?: VisageStyleSheet;
  // Group.ts
  Group?: VisageStyleSheet;
  // Header.ts
  Header?: VisageStyleSheet;
  // Image.tsx
  ImageContainer?: VisageStyleSheet;
  // Image.tsx
  Img?: VisageStyleSheet;
  // InlineError.tsx
  InlineError?: VisageStyleSheet;
  // InlineError.tsx
  InlineErrorIcon?: VisageStyleSheet;
  // TextInput.tsx
  InputExtraElement?: VisageStyleSheet;
  // Label.tsx
  Label?: VisageStyleSheet;
  // Link.ts
  Link?: VisageStyleSheet;
  // List.tsx
  ListContainer?: VisageStyleSheet;
  // List.tsx
  ListHeader?: VisageStyleSheet;
  // List.tsx
  ListItem?: VisageStyleSheet;
  // List.tsx
  ListItemLink?: VisageStyleSheet;
  // List.tsx
  ListItemsContainer?: VisageStyleSheet;
  // Loading.tsx
  LoadingProgressBar?: VisageStyleSheet;
  // Loading.tsx
  LoadingProgressBarProgress?: VisageStyleSheet;
  // Menu.tsx
  Menu?: VisageStyleSheet;
  // Menu.tsx
  MenuItem?: VisageStyleSheet;
  // Modal.tsx
  Modal?: VisageStyleSheet;
  // Pagination.tsx
  Pagination?: VisageStyleSheet;
  // Pagination.tsx
  PaginationNextPageButton?: VisageStyleSheet;
  // Pagination.tsx
  PaginationPreviousPageButton?: VisageStyleSheet;
  // Paragraph.tsx
  Paragraph?: VisageStyleSheet;
  // Paragraph.tsx
  ParagraphSkeleton?: VisageStyleSheet;
  // Popover.tsx
  Popover?: VisageStyleSheet;
  // Code.ts
  PreformattedCode?: VisageStyleSheet;
  // ProgressBar.tsx
  ProgressBar?: VisageStyleSheet;
  // ProgressBar.tsx
  ProgressBarProgress?: VisageStyleSheet;
  // Quotes.ts
  Quote?: VisageStyleSheet;
  // Radio.tsx
  RadioControl?: VisageStyleSheet;
  // Radio.tsx
  RadioLabel?: VisageStyleSheet;
  // Radio.tsx
  RadioLabelText?: VisageStyleSheet;
  // Radio.tsx
  RadioToggler?: VisageStyleSheet;
  // Layout.ts
  Row?: VisageStyleSheet;
  // Slider.tsx
  SliderThumb?: VisageStyleSheet;
  // Slider.tsx
  SliderTrack?: VisageStyleSheet;
  // Slider.tsx
  SliderTrackProgress?: VisageStyleSheet;
  // Text.tsx
  SmallText?: VisageStyleSheet;
  // Spinner.tsx
  SpinnerSvgBase?: VisageStyleSheet;
  // Text.tsx
  StrongText?: VisageStyleSheet;
  // Scripts.ts
  Subscript?: VisageStyleSheet;
  // Scripts.ts
  Superscript?: VisageStyleSheet;
  // Svg.ts
  Svg?: VisageStyleSheet;
  // SvgIcon.tsx
  SvgIconBase?: VisageStyleSheet;
  // Tabs.tsx
  TabList?: VisageStyleSheet;
  // Tabs.tsx
  TabNavigatonButton?: VisageStyleSheet;
  // Tabs.tsx
  Tabs?: VisageStyleSheet;
  // Text.tsx
  Text?: VisageStyleSheet;
  // TextArea.tsx
  TextArea?: VisageStyleSheet;
  // TextArea.tsx
  TextAreaBase?: VisageStyleSheet;
  // TextInput.tsx
  TextInputBase?: VisageStyleSheet;
  // TextInput.tsx
  TextInputControl?: VisageStyleSheet;
  // TextInput.tsx
  TextInputControlBase?: VisageStyleSheet;
  // Text.tsx
  TextSkeleton?: VisageStyleSheet;
  // Toast.tsx
  Toast?: VisageStyleSheet;
  // Toast.tsx
  ToastManager?: VisageStyleSheet;
  // Toggle.tsx
  ToggleContainer?: VisageStyleSheet;
  // Toggle.tsx
  ToggleControl?: VisageStyleSheet;
  // Toggle.tsx
  ToggleLabel?: VisageStyleSheet;
  // Toggle.tsx
  ToggleLabelText?: VisageStyleSheet;
  // Toggle.tsx
  ToggleToggler?: VisageStyleSheet;
  // Heading.tsx
  h1?: VisageStyleSheet;
  // Heading.tsx
  h2?: VisageStyleSheet;
  // Heading.tsx
  h3?: VisageStyleSheet;
  // Heading.tsx
  h4?: VisageStyleSheet;
  // Heading.tsx
  h5?: VisageStyleSheet;
  // Heading.tsx
  h6?: VisageStyleSheet;
  [componentName: string]: VisageStyleSheet | undefined;
}
